server:
  port: 9998
spring:
  application:
    name: server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/  #不作为客户端向注册中心注册
    register-with-eureka: false   #表示是否将自己注册到Eureka Server上，默认为true
    fetch-registry: false  #表示是否从Eureka Server上获取注册信息，默认为true